server:
  port: 8081
  application:
    name: "account-service"
spring:
  kafka:
    bootstrap-servers: localhost:9092
eureka:
  client:
    service-url:
      defaultZone: http://103.142.137.207:3000/eureka